package com.scoreMgr.model;

import com.scoreMgr.model.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {
	public static final Course dao = new Course().dao();
}
