package com.scoreMgr.model;

import com.scoreMgr.model.base.BaseScholarship;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scholarship extends BaseScholarship<Scholarship> {
	public static final Scholarship dao = new Scholarship().dao();
}
