package com.scoreMgr.model;

import com.scoreMgr.model.base.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	public static final Student dao = new Student().dao();
}
