package com.scoreMgr.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPno(java.lang.Integer pno) {
		set("pno", pno);
		return (M)this;
	}
	
	public java.lang.Integer getPno() {
		return getInt("pno");
	}

	public M setCredit(java.lang.Integer credit) {
		set("credit", credit);
		return (M)this;
	}
	
	public java.lang.Integer getCredit() {
		return getInt("credit");
	}

	public M setClazzhour(java.lang.Integer clazzhour) {
		set("clazzhour", clazzhour);
		return (M)this;
	}
	
	public java.lang.Integer getClazzhour() {
		return getInt("clazzhour");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public M setTUsername(java.lang.Integer tUsername) {
		set("t_username", tUsername);
		return (M)this;
	}
	
	public java.lang.Integer getTUsername() {
		return getInt("t_username");
	}

	public M setClazzid(java.lang.Integer clazzid) {
		set("clazzid", clazzid);
		return (M)this;
	}
	
	public java.lang.Integer getClazzid() {
		return getInt("clazzid");
	}

}
